name: Update README
on:
  workflow_dispatch:
    inputs:
      test_label:
        required: no
        type: string
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        uses: vnoctem/productive-box-in-readme@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: Russia/Moscow
          OWNER_REPO: 0nera
          PATH: README.md
